http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
credential.helper=manager-core
user.email=myemail
user.name=myusername
http.postbuffer=157286400
github.user=myusername
github.token=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
github.password=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
core.editor="C:\Users\Corton\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
